#!/bin/sh
# kvmhwd Rev2.1

start_usb_dev(){
    . /etc/profile
    . /kvmapp/system/init.d/S03usb-common
    echo "usb mode: device"
    cd /sys/kernel/config/usb_gadget

    mkdir g0
    cd g0

    echo 0x0200 > bcdUSB
    echo 0x0510 > bcdDevice
    # echo 0x3346 > idVendor
    # echo 0x1009 > idProduct
    if [ -e /boot/usb.vid ]
    then
        cat /boot/usb.vid > idVendor
    else
        echo 0x3346 > idVendor
    fi
    if [ -e /boot/usb.pid ]
    then
        cat /boot/usb.pid > idProduct
    else
        echo 0x1009 > idProduct
    fi
    write_usb_strings

    mkdir configs/c.1
    echo 0xE0 > configs/c.1/bmAttributes
    echo 120 > configs/c.1/MaxPower
    write_usb_config_string

    if [ -e /boot/usb.ncm ]
    then
        mkdir functions/ncm.usb0
        ln -s functions/ncm.usb0 configs/c.1/
    else
        if [ -e /boot/usb.rndis0 ]
        then
                mkdir functions/rndis.usb0
                ln -s functions/rndis.usb0 configs/c.1/
        fi
    fi

    if [ ! -e /boot/disable_hid ]
    then
        add_hid_function hid.GS0 1 1 8 '\x05\x01\x09\x06\xa1\x01\x05\x07\x19\xe0\x29\xe7\x15\x00\x25\x01\x75\x01\x95\x08\x81\x02\x95\x01\x75\x08\x81\x03\x95\x05\x75\x01\x05\x08\x19\x01\x29\x05\x91\x02\x95\x01\x75\x03\x91\x03\x95\x06\x75\x08\x15\x00\x25\xE7\x05\x07\x19\x00\x29\xE7\x81\x00\xc0'
        add_hid_function hid.GS1 1 2 4 '\x5\x1\x9\x2\xa1\x1\x9\x1\xa1\x0\x5\x9\x19\x1\x29\x3\x15\x0\x25\x1\x95\x3\x75\x1\x81\x2\x95\x1\x75\x5\x81\x3\x5\x1\x9\x30\x9\x31\x9\x38\x15\x81\x25\x7f\x75\x8\x95\x3\x81\x6\xc0\xc0'
        add_hid_function hid.GS2 '' 2 6 '\x05\x01\x09\x02\xa1\x01\x09\x01\xa1\x00\x05\x09\x19\x01\x29\x05\x15\x00\x25\x01\x95\x05\x75\x01\x81\x02\x95\x01\x75\x03\x81\x01\x05\x01\x09\x30\x09\x31\x15\x00\x26\xff\x7f\x35\x00\x46\xff\x7f\x75\x10\x95\x02\x81\x02\x05\x01\x09\x38\x15\x81\x25\x7f\x35\x00\x45\x00\x75\x08\x95\x01\x81\x06\xc0\xc0'
    fi

    if [ -e /boot/usb.disk0 ]
    then
            mkdir functions/mass_storage.disk0
            ln -s functions/mass_storage.disk0 configs/c.1/
            echo 1 > functions/mass_storage.disk0/lun.0/removable
            if [ -e /boot/usb.disk0.ro ]
            then
                    echo 1 > functions/mass_storage.disk0/lun.0/ro
                    echo 0 > functions/mass_storage.disk0/lun.0/cdrom
            fi
            printf '%s' "NanoKVM USB Mass Storage0520" > functions/mass_storage.disk0/lun.0/inquiry_string
            disk=$(cat /boot/usb.disk0)
            if [ -n "${disk}" ]
            then
                    cat /boot/usb.disk0 > functions/mass_storage.disk0/lun.0/file
            fi
    fi

    if [ -e /boot/usb.disk1 ]
    then
            mkdir functions/mass_storage.disk1
            ln -s functions/mass_storage.disk1 configs/c.1/
            echo 1 > functions/mass_storage.disk1/lun.0/removable
            printf '%s' "NanoKVM USB Data Disk0520" > functions/mass_storage.disk1/lun.0/inquiry_string
            echo /dev/mmcblk0p3 > functions/mass_storage.disk1/lun.0/file
    fi

    bind_first_udc
}

start_usb_host(){
    . /kvmapp/system/init.d/S03usb-common
    unbind_udc
    echo host > /proc/cviusb/otg_role
}

restart_usb_dev(){
    . /kvmapp/system/init.d/S03usb-common
    restart_udc
    echo "USB Restart OK!"
}

case "$1" in
  start)
    start_usb_dev
  ;;
  restart)
    restart_usb_dev
  ;;
  stop)
    start_usb_host
  ;;
  stop_start)
    start_usb_host
    start_usb_dev
  ;;
   restart_phy)
    echo "4340000.usb" > /sys/bus/platform/drivers/dwc2/unbind
    sleep 1
    echo "4340000.usb" > /sys/bus/platform/drivers/dwc2/bind
    start_usb_host
    start_usb_dev
  ;;
esac
