#!/bin/sh
# kvmhwd Rev2.2

# shellcheck source=/kvmapp/system/init.d/S03usb-common
. "${USB_COMMON:-/kvmapp/system/init.d/S03usb-common}"

USB_NCM_FUNC='ncm.usb0'
USB_RNDIS_FUNC='rndis.usb0'
USB_MASS_STORAGE_FUNC='mass_storage.disk0'
USB_MASS_STORAGE_INQUIRY='NanoKVM USB Mass Storage0520'
USB_CDROM_INQUIRY='NanoKVM USB CD/DVD-ROM  0520'
USB_DATA_DISK_INQUIRY='NanoKVM USB Data Disk0520'
USB_DATA_DISK_BACKING='/dev/mmcblk0p3'

write_composite_device_class(){
    echo 0xEF > bDeviceClass
    echo 0x02 > bDeviceSubClass
    echo 0x01 > bDeviceProtocol
}

add_ncm_function(){
    mkdir "functions/${USB_NCM_FUNC}"
    prepare_fake_ncm_function "${USB_NCM_FUNC}"
    echo WINNCM > "functions/${USB_NCM_FUNC}/os_desc/interface.ncm/compatible_id"
    ln -s "functions/${USB_NCM_FUNC}" configs/c.1/
}

add_rndis_function(){
    mkdir "functions/${USB_RNDIS_FUNC}"
    prepare_fake_rndis_function "${USB_RNDIS_FUNC}"
    echo e0 > "functions/${USB_RNDIS_FUNC}/class"
    echo 01 > "functions/${USB_RNDIS_FUNC}/subclass"
    echo 03 > "functions/${USB_RNDIS_FUNC}/protocol"
    echo RNDIS > "functions/${USB_RNDIS_FUNC}/os_desc/interface.rndis/compatible_id"
    echo 5162001 > "functions/${USB_RNDIS_FUNC}/os_desc/interface.rndis/sub_compatible_id"
    ln -s "functions/${USB_RNDIS_FUNC}" configs/c.1/
}

add_network_function(){
    if [ -e "${USB_BOOT_DIR}/usb.ncm" ]
    then
        add_ncm_function
    elif [ -e "${USB_BOOT_DIR}/usb.rndis0" ]
    then
        add_rndis_function
    else
        return 0
    fi

    echo 1 > os_desc/use
    echo 0xCD > os_desc/b_vendor_code
    echo MSFT100 > os_desc/qw_sign
    ln -s configs/c.1 os_desc
}

add_mass_storage_profile(){
    profile_backing="$1"
    profile_ro="$2"
    profile_cdrom="$3"
    profile_inquiry="$4"

    mkdir "functions/${USB_MASS_STORAGE_FUNC}"
    prepare_fake_lun "${USB_MASS_STORAGE_FUNC}"
    echo 1 > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/removable"
    echo "${profile_ro}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/ro"
    echo "${profile_cdrom}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/cdrom"
    printf '%s' "${profile_inquiry}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/inquiry_string"
    if [ -n "${profile_backing}" ]
    then
        printf '%s' "${profile_backing}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/file"
    fi
    ln -s "functions/${USB_MASS_STORAGE_FUNC}" configs/c.1/
}

trim_boot_file(){
    sed 's/^[[:space:]]*//; s/[[:space:]]*$//' "${USB_BOOT_DIR}/$1"
}

set_virtual_media_profile(){
    disk="$1"
    profile_ro=0
    profile_cdrom=0
    profile_backing=''
    profile_inquiry="${USB_MASS_STORAGE_INQUIRY}"

    if [ -n "${disk}" ] && [ "${disk}" != "${USB_DATA_DISK_BACKING}" ]
    then
        profile_backing="${disk}"
        if [ -e "${USB_BOOT_DIR}/usb.media0.cdrom" ]
        then
            profile_ro=1
            profile_cdrom=1
            profile_inquiry="${USB_CDROM_INQUIRY}"
        elif [ -e "${USB_BOOT_DIR}/usb.media0.ro" ]
        then
            profile_ro=1
        fi
    fi

    printf '%s\n%s\n%s\n%s\n' "${profile_backing}" "${profile_ro}" "${profile_cdrom}" "${profile_inquiry}"
}

set_data_disk_profile(){
    printf '%s\n%s\n%s\n%s\n' "${USB_DATA_DISK_BACKING}" 0 0 "${USB_DATA_DISK_INQUIRY}"
}

add_selected_mass_storage_profile(){
    profile="$1"
    profile_backing=$(printf '%s\n' "${profile}" | sed -n '1p')
    profile_ro=$(printf '%s\n' "${profile}" | sed -n '2p')
    profile_cdrom=$(printf '%s\n' "${profile}" | sed -n '3p')
    profile_inquiry=$(printf '%s\n' "${profile}" | sed -n '4p')
    add_mass_storage_profile \
        "${profile_backing}" \
        "${profile_ro}" \
        "${profile_cdrom}" \
        "${profile_inquiry}"
}

add_boot_mass_storage_function(){
    media_disk=''
    if [ -e "${USB_BOOT_DIR}/usb.media0" ]
    then
        media_disk=$(trim_boot_file usb.media0)
    fi

    if [ -e "${USB_BOOT_DIR}/usb.media0" ] && { [ "${media_disk}" != "${USB_DATA_DISK_BACKING}" ] || [ ! -e "${USB_BOOT_DIR}/usb.disk0" ]; }
    then
        add_selected_mass_storage_profile "$(set_virtual_media_profile "${media_disk}")"
    elif [ -e "${USB_BOOT_DIR}/usb.disk0" ]
    then
        add_selected_mass_storage_profile "$(set_data_disk_profile)"
    fi
}

start_usb_dev(){
    prepare_usb_gadget "${USB_NORMAL_BCD_USB}" "${USB_NORMAL_BCD_DEVICE}" "${USB_NORMAL_CONFIG_ATTRIBUTES}" "${USB_NORMAL_MAX_POWER}"
    write_composite_device_class

    add_network_function

    if [ ! -e "${USB_BOOT_DIR}/disable_hid" ]
    then
        add_hid_functions "${USB_HID_REPORT_NORMAL_KEYBOARD}" "${USB_HID_REPORT_NORMAL_ABSOLUTE_MOUSE}"
    fi

    add_boot_mass_storage_function

    bind_first_udc
}

run_usb_action "$1"
