#!/bin/sh
# kvmhwd Rev2.1

# shellcheck source=/kvmapp/system/init.d/S03usb-common
. "${USB_COMMON:-/kvmapp/system/init.d/S03usb-common}"

USB_NCM_FUNC='ncm.usb0'
USB_RNDIS_FUNC='rndis.usb0'
USB_MASS_STORAGE_FUNC='mass_storage.disk0'
USB_MASS_STORAGE_INQUIRY='NanoKVM USB Mass Storage0520'
USB_CDROM_INQUIRY='NanoKVM USB CD/DVD-ROM  0520'
USB_DATA_DISK_INQUIRY='NanoKVM USB Data Disk0520'
USB_DATA_DISK_BACKING='/dev/mmcblk0p3'

add_mass_storage_function(){
    backing="$1"
    ro="$2"
    cdrom="$3"
    inquiry="$4"

    mkdir "functions/${USB_MASS_STORAGE_FUNC}"
    echo 1 > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/removable"
    echo "${ro}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/ro"
    echo "${cdrom}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/cdrom"
    printf '%s' "${inquiry}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/inquiry_string"
    if [ -n "${backing}" ]
    then
        printf '%s' "${backing}" > "functions/${USB_MASS_STORAGE_FUNC}/lun.0/file"
    fi
    ln -s "functions/${USB_MASS_STORAGE_FUNC}" configs/c.1/
}

trim_boot_file(){
    sed 's/^[[:space:]]*//; s/[[:space:]]*$//' "${USB_BOOT_DIR}/$1"
}

add_virtual_media_function(){
    disk="$1"
    media_ro=0
    media_cdrom=0
    media_backing=''
    media_inquiry="${USB_MASS_STORAGE_INQUIRY}"

    if [ -n "${disk}" ] && [ "${disk}" != "${USB_DATA_DISK_BACKING}" ]
    then
        media_backing="${disk}"
        if [ -e "${USB_BOOT_DIR}/usb.media0.cdrom" ]
        then
            media_ro=1
            media_cdrom=1
            media_inquiry="${USB_CDROM_INQUIRY}"
        elif [ -e "${USB_BOOT_DIR}/usb.media0.ro" ]
        then
            media_ro=1
        fi
    fi

    add_mass_storage_function "${media_backing}" "${media_ro}" "${media_cdrom}" "${media_inquiry}"
}

add_data_disk_function(){
    add_mass_storage_function "${USB_DATA_DISK_BACKING}" 0 0 "${USB_DATA_DISK_INQUIRY}"
}

add_boot_mass_storage_function(){
    media_disk=''
    if [ -e "${USB_BOOT_DIR}/usb.media0" ]
    then
        media_disk=$(trim_boot_file usb.media0)
    fi

    if [ -e "${USB_BOOT_DIR}/usb.media0" ] && { [ "${media_disk}" != "${USB_DATA_DISK_BACKING}" ] || [ ! -e "${USB_BOOT_DIR}/usb.disk0" ]; }
    then
        add_virtual_media_function "${media_disk}"
    elif [ -e "${USB_BOOT_DIR}/usb.disk0" ]
    then
        add_data_disk_function
    fi
}

start_usb_dev(){
    prepare_usb_gadget "${USB_NORMAL_BCD_USB}" "${USB_NORMAL_BCD_DEVICE}" "${USB_NORMAL_CONFIG_ATTRIBUTES}" "${USB_NORMAL_MAX_POWER}"

    if [ -e "${USB_BOOT_DIR}/usb.ncm" ]
    then
        mkdir "functions/${USB_NCM_FUNC}"
        ln -s "functions/${USB_NCM_FUNC}" configs/c.1/
    elif [ -e "${USB_BOOT_DIR}/usb.rndis0" ]
    then
        mkdir "functions/${USB_RNDIS_FUNC}"
        ln -s "functions/${USB_RNDIS_FUNC}" configs/c.1/
    fi

    if [ ! -e "${USB_BOOT_DIR}/disable_hid" ]
    then
        add_hid_functions "${USB_HID_REPORT_NORMAL_KEYBOARD}" "${USB_HID_REPORT_NORMAL_ABSOLUTE_MOUSE}"
    fi

    add_boot_mass_storage_function

    bind_first_udc
}

run_usb_action "$1"
