#!/bin/sh

. /etc/profile

APFLAG_FILE=/run/nanokvm/wifiap

gen_hostapd_conf() {
    ssid="${1}"
    pass="${2}"
    echo "ctrl_interface=/var/run/hostapd"
    echo "ctrl_interface_group=0"
    printf '%s\n' "ssid=${ssid}"
    echo "hw_mode=g"
    echo "channel=1"
    echo "beacon_int=100"
    echo "dtim_period=2"
    echo "max_num_sta=8"
    echo "rts_threshold=-1"
    echo "fragm_threshold=-1"
    echo "macaddr_acl=0"
    echo "auth_algs=3"
    echo "wpa=2"
    printf '%s\n' "wpa_passphrase=${pass}"
    echo "ieee80211n=1"
}

gen_udhcpd_conf() {
    interface=${1}
    ipv4_prefix=${2}
    echo "start ${ipv4_prefix}.100"
    echo "end ${ipv4_prefix}.200"
    echo "interface ${interface}"
    echo "pidfile /var/run/udhcpd.${interface}.pid"
    echo "lease_file /var/lib/misc/udhcpd.${interface}.leases"
    echo "option subnet 255.255.255.0"
    echo "option lease 600"
}

gen_dnsmasq_conf() {
    ipv4_prefix=${1}
    echo "bind-interfaces"
    echo "interface=wlan0"
    echo "address=/config.kvm/${ipv4_prefix}.1"
    echo "no-hosts"
    echo "dhcp-range=${ipv4_prefix}.2,${ipv4_prefix}.254"
    echo "dhcp-option=6,${ipv4_prefix}.1"
    echo "dhcp-option=3,${ipv4_prefix}.1"
    echo "dhcp-authoritative"
}

start() {
    echo "wifi mode: sta"
    ssid=""
    pass=""
    if [ -e /boot/wifi.ssid ] && [ -e /boot/wifi.pass ]; then
        echo "Updating WiFi credentials from /boot to /etc/kvm/"

        install -m 0644 -o root -g root /boot/wifi.ssid /etc/kvm/wifi.ssid
        install -m 0600 -o root -g root /boot/wifi.pass /etc/kvm/wifi.pass

        chown root:root /etc/kvm/wifi.ssid /etc/kvm/wifi.pass
        chmod 644 /etc/kvm/wifi.ssid
        chmod 600 /etc/kvm/wifi.pass
    fi
    if [ -e /etc/kvm/wifi.ssid ]; then
        ssid=$(sed -n '1p' /etc/kvm/wifi.ssid)
    fi
    if [ -e /etc/kvm/wifi.pass ]; then
        pass=$(sed -n '1p' /etc/kvm/wifi.pass)
    fi
    wpa_tmp="$(mktemp /etc/wpa_supplicant.conf.XXXXXX)"
    echo "ctrl_interface=/var/run/wpa_supplicant" >"$wpa_tmp"
    wpa_passphrase "$ssid" "$pass" >>"$wpa_tmp"
    chmod 600 "$wpa_tmp"
    mv "$wpa_tmp" /etc/wpa_supplicant.conf
    chmod 600 /etc/wpa_supplicant.conf
    wpa_supplicant -B -i wlan0 -c /etc/wpa_supplicant.conf
    if [ ! -e /boot/wifi.nodhcp ]; then
        (udhcpc -i wlan0 -t 10 -T 1 -A 5 -b -p /run/udhcpc.wlan0.pid) &
    fi
}

ap_start() {
    echo "wifi mode: ap"
    id2=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 2))
    id3=$(printf "%d" 0x$(sha512sum /sys/class/cvi-base/base_uid | head -c 4 | tail -c 2))
    if [ "$id2" = "$id3" ]; then
        id2=$((id2 + 1))
    fi
    if [ "$id2" -ge 255 ]; then
        id2=253
    fi
    if [ "$id3" -ge 255 ]; then
        id3=254
    fi
    ssid=""
    pass=""
    if [ -e /kvmapp/kvm/ap.ssid ]; then
        ssid=$(cat /kvmapp/kvm/ap.ssid)
    fi
    if [ -e /kvmapp/kvm/ap.pass ]; then
        pass=$(sed -n '1p' /kvmapp/kvm/ap.pass)
    fi
    hostapd_tmp="$(mktemp /etc/hostapd.conf.XXXXXX)"
    gen_hostapd_conf "$ssid" "$pass" >"$hostapd_tmp"
    chmod 600 "$hostapd_tmp"
    mv "$hostapd_tmp" /etc/hostapd.conf
    chmod 600 /etc/hostapd.conf
    ipv4_prefix=10.$id3.$id2
    if [ ! -e /etc/udhcpd.wlan0.conf ]; then
        gen_udhcpd_conf wlan0 "${ipv4_prefix}" >/etc/udhcpd.wlan0.conf
    fi
    # gen_dnsmasq_conf "${ipv4_prefix}"  > /etc/dnsmasq.conf

    # iptables --policy INPUT ACCEPT
    # iptables --policy FORWARD ACCEPT
    # iptables --policy OUTPUT ACCEPT
    # iptables -F
    # iptables -t nat -F
    # iptables -t nat -A PREROUTING -i wlan0 -p udp --dport 53 -j DNAT --to ${ipv4_prefix}.1

    ifconfig wlan0 up
    ip route replace default dev wlan0 metric 4096 || true
    ip addr replace $ipv4_prefix.1/24 dev wlan0
    # dnsmasq --pid-file=/tmp/dnsmasq.run -C /etc/dnsmasq.conf
    hostapd -B -P /run/hostapd.wlan0.pid -i wlan0 /etc/hostapd.conf
    udhcpd -S -p /run/udhcpd.wlan0.pid /etc/udhcpd.wlan0.conf

    if [ ! -f "$APFLAG_FILE" ]; then
        mkdir -p "$(dirname "$APFLAG_FILE")"
        install -m 0600 /dev/null "$APFLAG_FILE"
    fi

}

stop() {
    if [ -s /run/hostapd.wlan0.pid ]; then
        read -r pid </run/hostapd.wlan0.pid
        case "$pid" in (*[!0-9]*|'') ;; (*) kill -2 "$pid" || true ;; esac
        rm -f /run/hostapd.wlan0.pid
    fi
    if [ -s /run/udhcpd.wlan0.pid ]; then
        read -r pid </run/udhcpd.wlan0.pid
        case "$pid" in (*[!0-9]*|'') ;; (*) kill -2 "$pid" || true ;; esac
        rm -f /run/udhcpd.wlan0.pid
    fi
    killall wpa_supplicant || true
    if [ -e /run/udhcpc.wlan0.pid ]; then
        read -r pid </run/udhcpc.wlan0.pid
        case "$pid" in (*[!0-9]*|'') ;; (*) kill "$pid" || true ;; esac
        rm -f /run/udhcpc.wlan0.pid
    fi
    if [ -e /var/run/udhcpd.wlan0.pid ]; then
        read -r pid </var/run/udhcpd.wlan0.pid
        case "$pid" in (*[!0-9]*|'') ;; (*) kill "$pid" || true ;; esac
        rm -f /var/run/udhcpd.wlan0.pid
    fi
    if [ -e /tmp/dnsmasq.run ]; then
        read -r pid </tmp/dnsmasq.run
        case "$pid" in (*[!0-9]*|'') ;; (*) kill "$pid" || true ;; esac
        rm -f /tmp/dnsmasq.run
    fi
    # if [ -e /etc/wpa_supplicant.conf]
    # then
    # 	echo > /etc/wpa_supplicant.conf
    # fi
    # monitor-mode cleanup is handled by the Wi-Fi driver reset path

    if [ -f "$APFLAG_FILE" ]; then
        rm "$APFLAG_FILE"
    fi
}

restart() {
    stop
    start
}

if [ "${1}" = "start" ]; then
    start
elif [ "${1}" = "stop" ]; then
    stop
elif [ "${1}" = "ap" ]; then
    stop
    ap_start
elif [ "${1}" = "restart" ]; then
    restart
fi
